### ISSUE TITLE
Add a sidecar container to NFs

### ISSUE THREAD

**Issue by hinddeep** [Gradiant/openverso-charts#108]
I have created a sidecar container image. I want to run this image as a sidecar container in NF such as amf. How can I modify AMF's chart to add my sidecar container?

**Comment by cgiraldo** [comment]
Hi Hindeep,

Our helm charts have a configurable field in values.yaml call `sidecars`.
You can add the yaml description of your sidecar for the corresponding NF. For example, for the amf, something like this:
```
amf:
  sidecars:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
```

The contents of `sidecars` are also evaluated as a template, so you can include `{{ }}` and refer to other helm variables. Checkout Helm Documentation for advanced usage.

**Comment by hinddeep** [comment]
I navigated to openverso-charts/charts/open5gs-amf/values.yaml and added the following code in values.yaml under sidecars:

```
sidecars:
- name: myimg
  image: img:0.0.1
  ports:
  - containerPort: 9090
 ```

I then tried to install amf using the following command: 
```
helm install amf -n open5gs ./charts/open5gs-amf
```

I received the following error:
```
Error: INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: common
```
