### ISSUE TITLE
multiple UPFs on 5GC in smf.yaml

### ISSUE THREAD

**Issue by jmarkotic** [Gradiant/openverso-charts#112]
Hi,
i wanted to setup 5G core with having 2 UPFs, each serving single DNN. I.e. one upf is to be instantiated on cluster with rest of 5gc, and other would be instantiated as standalone on different cluster (i.e. Edge).
I am stuck on how to set smf configuration to be aware of both UPF PFCP IPs . I would need to define list of pfcp ip and relate it to DNN. I'd need something in smf.yaml like:
```
 upf:
     pfcp:
       - addr: upf1-ip
           dnn: internet
       - addr: upf2-ip
           dnn: compX-apn
```
For what i can see, in smf.yaml config file there is only option to define single upf pfcp ip (and not list).
I might be able to do some crude code rewrite in resources/smf.yaml to support multiple UPFs (And related DNNs), but i was wondering if this is already supported in different way.
I can see variable .Values.customOpen5gsConfig but not sure how to put config file in there. Seems that way would not trigger resolving of helm variables.
Any suggestion ?
br,
j
