### ISSUE TITLE
NFs retrying to register to NRF (Open5GS 2.6.4)

### ISSUE THREAD

**Issue by swinarga** [Gradiant/openverso-charts#133]
Hello!
I was trying to see if I could run Open5GS version 2.6.4 but there seems to be a problem with the network functions not registering to the NRF.  I installed the chart with the following command: `helm install open5gs openverso/open5gs --version 2.0.12 --values=values.yaml`

**values.yaml:**
```
hss:
  enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
smf:
  config:
    pcrf:
      enabled: false
  image:
    tag: "2.6.4"
sgwc:
  enabled: false
sgwu:
  enabled: false
amf:
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac:
          - 1
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"
  image:
    tag: "2.6.4"
ausf:
  image:
    tag: "2.6.4"
bsf:
  image:
    tag: "2.6.4"
nrf:
  image:
    tag: "2.6.4"
nssf:
  config:
    nsiList:
      - nrf:
          hostname: ""
          port: 7777
        sst: 1
        sd: "0x111111"
  image:
    tag: "2.6.4"
pcf:
  image:
    tag: "2.6.4"
udm:
  image:
    tag: "2.6.4"
udr:
  image:
    tag: "2.6.4"
upf:
  image:
    tag: "2.6.4"
webui:
  ingress:
    enabled: false
  image:
    tag: "2.6.4"
populate:
  image:
    tag: "0.10.3"
  enabled: true
  initCommands:
    - open5gs-dbctl add_ue_with_slice 999700000000001
      465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet
      1 111111
    - open5gs-dbctl add_ue_with_slice 999700000000002
      465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet
      1 111111

```
**AMF logs:**
![amf_logs](https://github.com/Gradiant/openverso-charts/assets/53258224/685fe9b1-ca9e-4e28-b4e3-efb93d5079e4)

**NRF - only the NRF itself is registered:**
![nrf_registered_nfs](https://github.com/Gradiant/openverso-charts/assets/53258224/372f7c00-1011-4add-8d53-c8db16e5c92f)
