### ISSUE TITLE
ingressClassName not used in webui ingress template

### ISSUE THREAD

**Issue by anabel1012** [Gradiant/openverso-charts#140]
Hello!
I was trying to configure the ingress service for webui as nginx type. I have seen that the variable ingressClassName is defined in the values.yaml of webui/templates but then it is not used in webui/templates/ingress.yaml.

Correct me if I'm wrong, but I think there is a line missing in the charts/open5gs-webui/templates/ingress.yaml file. 

```
spec:
  ingressClassName: ... (to add)
  rules:
    - host: {{ .Values.ingress.hostname | default (printf "%s-%s.ingress.lab5g.gradiant.org" .Release.Name .Release.Namespace) }}
``` 

If not, please, could you help me with this ingress type nginx?

Thanks,
Anabel
